# === ???????????? ??????? ===
# ???????????? ???? ??????? (??????? 8080)
server.port=8090

# === ???????????? Spring ===
# ???? ???????? ????? ????????
spring.application.name=book-catalog

# === ???????????? H2 (DataSource) ===
# Spring Boot ??????????? ???????? H2
# ???????? URL (????? ?????, ?? ? ???? 2)
spring.datasource.url=jdbc:h2:file:./data/catalog;AUTO_SERVER=TRUE
# ???????? ??????????? ?? ??????
spring.datasource.username=sa
spring.datasource.password=
# ???????? H2 ???????
spring.datasource.driver-class-name=org.h2.Driver
# ?????????? H2 ??????? (??????? ???? Spring)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# ????????? ????????? schema.sql ?? data.sql ??? ??????? ??????
spring.sql.init.mode=always