CREATE TABLE IF NOT EXISTS books (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     title VARCHAR(255) NOT NULL,
    author VARCHAR(100) NOT NULL,
    description VARCHAR(2000)
    );

CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        book_id BIGINT NOT NULL,
                                        author VARCHAR(64) NOT NULL,
    text VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                             FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
    );