package ua.com.lab.persistence;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class H2Database {
    private static final Logger log = LoggerFactory.getLogger(H2Database.class);
    private static final String H2_URL = "jdbc:h2:file:./data/catalog;AUTO_SERVER=TRUE";
    private static final String H2_USER = "sa";
    private static final String H2_PASS = "";

    public H2Database() {
        try {
            Class.forName("org.h2.Driver");
        } catch (ClassNotFoundException e) {
            throw new RuntimeException("H2 Driver not found!", e);
        }
    }

    public Connection getConnection() throws SQLException {
        return DriverManager.getConnection(H2_URL, H2_USER, H2_PASS);
    }

    public void initialize() {
        log.info("Initializing database schema...");
        String createBooksTable = """
            CREATE TABLE IF NOT EXISTS books (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                author VARCHAR(100) NOT NULL,
                description VARCHAR(2000)
            )
            """;

        String createCommentsTable = """
            CREATE TABLE IF NOT EXISTS comments (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                book_id BIGINT NOT NULL,
                author VARCHAR(64) NOT NULL,
                text VARCHAR(1000) NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
            )
            """;

        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute(createBooksTable);
            stmt.execute(createCommentsTable);

            try (var rs = stmt.executeQuery("SELECT COUNT(*) FROM books")) {
                if (rs.next() && rs.getInt(1) == 0) {
                    log.info("Populating database with sample data...");
                    stmt.execute("INSERT INTO books (title, author, description) VALUES " +
                            "('The Lord of the Rings', 'J.R.R. Tolkien', 'An epic fantasy novel.')," +
                            "('1984', 'George Orwell', 'A dystopian social science fiction novel and cautionary tale.')," +
                            "('Dune', 'Frank Herbert', 'A 1965 epic science fiction novel.')");
                }
            }
            log.info("Database initialized successfully.");
        } catch (SQLException e) {
            log.error("Failed to initialize database", e);
            throw new RuntimeException("Database initialization failed", e);
        }
    }
}